### ISSUE TITLE
This project can't be run yet, right?

### ISSUE THREAD

**Issue by RobotsRuning** [adityamwagh/SuperSLAM#1]
**I'm getting some of the following errors that can't be modified**

CMake Error at CMakeLists.txt:111 (add_executable):
  Cannot find source file:

    Examples/RGB-D/rgbd_tum.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:117 (add_executable):
  Cannot find source file:

    Examples/Stereo/stereo_kitti.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:121 (add_executable):
  Cannot find source file:

    Examples/Stereo/stereo_euroc.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:127 (add_executable):
  Cannot find source file:

    Examples/Monocular/mono_tum.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:131 (add_executable):
  Cannot find source file:

    Examples/Monocular/mono_kitti.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:135 (add_executable):
  Cannot find source file:

    Examples/Monocular/mono_euroc.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:111 (add_executable):
  No SOURCES given to target: rgbd_tum

CMake Error at CMakeLists.txt:117 (add_executable):
  No SOURCES given to target: stereo_kitti

CMake Error at CMakeLists.txt:121 (add_executable):
  No SOURCES given to target: stereo_euroc

CMake Error at CMakeLists.txt:127 (add_executable):
  No SOURCES given to target: mono_tum

CMake Error at CMakeLists.txt:131 (add_executable):
  No SOURCES given to target: mono_kitti

CMake Error at CMakeLists.txt:135 (add_executable):
  No SOURCES given to target: mono_euroc

**Comment by adityamwagh** [comment]
Nope! sorry, it's a work in progress! I've to fix a bunch of things with it before anyone can use it directly. Busy with a bunch of other things right now.

**Comment by ZhangshenHuang** [comment]
Do you know  any other open-source solutions that embed SuperPoint and SuperGlue into SLAM frameworks?

**Comment by ZhangshenHuang** [comment]
> Nope! sorry, it's a work in progress! I've to fix a bunch of things with it before anyone can use it directly. Busy with a bunch of other things right now.

Thank you for making your current work public. I'm really looking forward to your update.

**Comment by adityamwagh** [comment]
> Do you know any other open-source solutions that embed SuperPoint and SuperGlue into SLAM frameworks?

Sorry, I'm not aware of any. I'm sure someone else might also be working on it.

**Comment by zhangsngood** [comment]
> Do you know any other open-source solutions that embed SuperPoint and SuperGlue into SLAM frameworks?

Now, do you know any other open-source solutions that embed SuperPoint and SuperGlue into SLAM frameworks? I'm also looking for similar working code.

**Comment by RobotsRuning** [comment]
This is a challenge  work 。暂时没有发现相关工作被开源，我决定自己写了。发自我的iPhone------------------ Original ------------------From: zhangsngood  ***@***.***>Date: Sun,Apr 7,2024 3:57 PMTo: adityamwagh/SuperSLAM ***@***.***>Cc: RobotsRuning ***@***.***>, Author ***@***.***>Subject: Re: [adityamwagh/SuperSLAM] This project can't be run yet, right?(Issue #1)

Do you know any other open-source solutions that embed SuperPoint and SuperGlue into SLAM frameworks?

Now, do you know any other open-source solutions that embed SuperPoint and SuperGlue into SLAM frameworks? I'm also looking for similar working code.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/adityamwagh/SuperSLAM/issues/1#issuecomment-2041357417",
"url": "https://github.com/adityamwagh/SuperSLAM/issues/1#issuecomment-2041357417",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by adityamwagh** [comment]
You can try this: https://github.com/klammecr/superslam

**Comment by adityamwagh** [comment]
@RobotsRuning @ZhangshenHuang @zhangsngood  please try running the repo again. Still a lot of work to do but it seems to be in a working stage. I made it a lot easier for people to run this code now.
