### ISSUE TITLE
Has this work been completed?

### ISSUE THREAD

**Issue by zhangsngood** [adityamwagh/SuperSLAM#2]
Hello, thank you for your contribution. I am very interested in this work, has it been completed?

**Comment by adityamwagh** [comment]
No, sorry it needs more work. A little busy with a few things. I’ll let you know on this thread when I complete it.

**Comment by antithing** [comment]
Watching..

**Comment by adityamwagh** [comment]
@zhangsngood please try running the repo again. Still a lot of work to do but it seems to be in a working stage. I made it a lot easier for people to run this code now.

**Comment by zhangsngood** [comment]
@adityamwagh Hello! Thank you for your work! I would like to know how the results of this repository are currently, and are there any corresponding result images displayed?
