### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by hongshaoqiu** [adityamwagh/SuperSLAM#4]
Hello,thanks a lot for your work!
When i make this repo,i encountered the errors shown in the image.
![1721804117485](https://github.com/user-attachments/assets/8118a939-361d-4f3b-807c-b8c1895bb284)
hen i make this repo,i encountered the errors shown in the image.

How should I run this project? Should I write a 'build.sh' script similar to ORB_SLAM2?

**Comment by adityamwagh** [comment]
Working on fixing it, will update you here when done.

**Comment by hongshaoqiu** [comment]
> Working on fixing it, will update you here when done.
OK, Thank you very much for your efforts.
