### ISSUE TITLE
Work in progress

### ISSUE THREAD

**Issue by dubing-bit** [adityamwagh/SuperSLAM#5]
Hi, is this work done please, I seem to be able to compile it and complete it, but it is not tested. Do you have a tested example please?

**Comment by Dmm66-lang** [comment]
兄弟你好啊，这个作者的代码你能通过编译吗？我卡在最后一步上了，说是make[2]: *** 没有规则可制作目标“../libtorch-cxx11-abi-shared-with-deps-2.4.0+cu118/libtorch/lib/libc10.so”，由“../lib/libSuperSLAM.so” 需求。 停止。
make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/SuperSLAM.dir/all] 错误 2
想请教下你，这是啥问题呀

**Comment by dubing-bit** [comment]
我没有遇到这个问题，不过明显是你的LibTorch的问题，首先需要检查你的libtorch版本与CUDA是否对应。其次，下载解压libtorch 并在CMakeLists.txt中正确设置libtorch路径`set(Torch_DIR "/home/ubuntu/pytorch_master/pytorch/torch/share/cmake/Torch")  # libtorch`

**Comment by ddkats** [comment]
@dubing-bit Did you manage to run it?

@adityamwagh Is this work still in progress? Can you elaborate a bit on what is not done yet?

**Comment by adityamwagh** [comment]
@ddkats I've paused working on it for now. I will be rebasing off of a MIT Licenced SLAM Implementation or write the backend myself in the near future. No ETA.

Please try this meanwhile - https://github.com/klammecr/superslam
